public class Calculator {
    public static void sumOfTwo(Integer a,Integer b)
    {
        System.debug('Sum of two numbers: ' + (a+b));
    }
	public static void multiplicationOfTwo(Integer a,Integer b)
    {
        System.debug('Multiplication of two numbers: ' + (a*b));
    }

    public static void subtractionOfTwo(Integer a,Integer b)
    {
        System.debug('Subtraction of two numbers: ' + (a-b));
    }
	 public static void divisionOfTwo(	double a, double b)
    {
        System.debug('Division of two numbers: ' + (a/b));
    }

}